-- comment Database


INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('great man',26,6);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('looking greate bhai',12,17);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('nice place keep enjoying',29,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('great bhai meetu soon ',49,21);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('aag lga di bhai',37,34);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('briallant keep working',3,34);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('soon will join you all',86,21);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('nice man !! loved it',81,28);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('bawnadar aayega abb ',83,48);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('boht tezz ho rhe ho ',38,23);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('bade acche ho beta',92,27);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('rakh neeche rakh teri toh',83,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('kaise ho bro',5,50);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('aag lga di h bss fire extinguisher bulana pdega',42,4);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('ek kahani h jo sabko sunnani h jakne wako ki toh rooh bhi jaalani h',59,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('mast h bhai , mill tabb btata hu kon mast h ',62,31);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('sahi lgg rha h bss ',27,8);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I think this is the best I’ve seen till now.',83,36);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' Not enough for me, you are everything.',34,13);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' Just when I couldn’t love you more. You posted this pic and my jaw dropped to the floor.',81,46);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are a symbol of beauty.',77,38);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' Surely you are the most beautiful woman alive, the most that I’ve seen.',96,19);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You mean the world to me.',58,10);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('The word pretty is worthless without you.',64,44);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are the definition of Beauty',81,4);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Flawless outstanding eccentric lovely beauty.',36,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('The stars, the moon, and the sun are minor to me since you sparkle brighter than all of them.',45,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are graceful.',21,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' Surely you would have been arrested if looking immensely beautiful was a crime.',3,46);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You’re an incredibly stunning, a really pretty, beautiful woman.',51,39);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' I guess this is your best look, you look beautiful in this outfit.',37,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You look mesmerizing.',68,22);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I wonder how cute you would be looking when you sleep.',6,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are so much lovely.',29,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I love your curly hair.',2,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Your dressing sense is appreciable.',39,41);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' You are the sweetest girl I have ever seen.',40,33);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. I love that straight hair of yours.',79,29);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are pleasing.',45,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Just ‘WOW’ for your natural beauty.',41,33);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are cute.',18,49);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I love how comfortable you are in your world.',45,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are very much adorable.',39,5);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You look even more pretty without makeup.',47,45);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I feel so happy to be with you.',85,13);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are my safest place.',51,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You look beautiful in that dress.',99,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. I wish I had your makeup.',5,23);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are stunning.',78,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. That natural beauty tho.',25,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You have the most beautiful, sparkling eyes.',86,46);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You have the most beautiful smile.',70,10);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. Your sense of fashion is great.',70,22);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' I like your hair.',25,32);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. You look more beautiful than in the photo.',24,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' You look stunning.',94,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You’re classy.',89,34);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' You’re very trendy',100,1);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Landscape/Scenery:',75,40);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Great shot!',82,29);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Nice shot!!',93,6);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Love the view.',74,31);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Did you have fun up there?',46,11);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Selfie/picture of themselves:',13,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Looking good!',31,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Pretty/beautiful!',57,44);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Handsome!',58,39);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('OH MAH GOSH!!',35,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('?????? (three heart-eyed emojis)',20,43);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Sexy pose of themselves:',98,31);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('MESSY!',84,36);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('OMG!',29,42);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('OMG! Be my wife or dad already!!',100,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Hot',3,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('?????? (three heart-eyed emojis)',44,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Wtf, how are you so pretty/handsome?',42,19);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Wow!! In love!!',32,19);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Classic',59,6);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Picture of their outfit or OOTD (outfit of the day):',99,9);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Ou la la',25,32);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Gorgeous!!',12,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Love your outfit!!',71,1);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Looking good, man.',2,33);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('A picture of their pet/pets:',26,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Soooooo cute!!',48,44);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('cute!',18,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('lovely pet you got there!',22,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('An inspirational quote:',36,48);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Inspired! Thanks for the share.',66,12);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Needed that, thanks!',11,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I agree/disagree.',13,21);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Inspirational',94,13);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('A picture of their family or children:',28,26);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Lovely children.',29,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Adorable kids, you got there!',76,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('They will grow up so fast!',6,23);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I remember when they were X small!! Time flies by to fast!',80,24);
